### ISSUE TITLE
Instructions needed.

### ISSUE THREAD

**Issue by dukc** [PetarKirov/dlang.nix#10]
There should be an instruction file for the user to build the derivations here. It should specify both how to simply build an already fetched version of a single package (copying what `readme.md` in OldDDerivations says probably does pretty good job) and how to run the prefetcher scripts to generate the version-specific hash files (once #9 is in).

**Comment by PetarKirov** [comment]
In PR #9 I've added a readme doc which covers the end-user aspects of using this repository - both via Flakes and the old-school way. In a future PR I plan rework the scripts and I'll add documentation for contributors. Please review https://github.com/PetarKirov/dlang.nix/blob/main/README.md and let me know what you think @dukc. I'm closing the issue for, but feel free to reopen it if needed.

**Comment by dukc** [comment]
Had a look. Yes, I'd say this satisfies what I wanted, and we don't need `2.xxx.nix` files anymore. Which is good since the new way is so much better automated.
